import { Department, LeadStatus, UserProfile, Lead, LeadActivity, Followup } from '../types/crm';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-ayurveda',
    name: 'Ayurveda Sales',
    description: 'Herbal remedies, wellness supplements, daily health packs & consultation packages',
    active: true,
    created_at: new Date('2026-01-10T09:00:00Z').toISOString(),
  },
  {
    id: 'dept-astrology',
    name: 'Astrology',
    description: 'Personalized horoscope analysis, gemstone recommendations & puja consultations',
    active: true,
    created_at: new Date('2026-01-10T09:15:00Z').toISOString(),
  },
  {
    id: 'dept-homedecor',
    name: 'Home Decor',
    description: 'Vastu brass idols, aromatherapy diffusers, authentic copper ware & sacred artifacts',
    active: true,
    created_at: new Date('2026-01-12T10:00:00Z').toISOString(),
  },
  {
    id: 'dept-reorder',
    name: 'Reorder',
    description: 'Repeat orders, loyalty subscriptions & follow-up refills for existing clients',
    active: true,
    created_at: new Date('2026-01-15T11:00:00Z').toISOString(),
  },
  {
    id: 'dept-support',
    name: 'Customer Support',
    description: 'Shipment tracking, courier status & post-purchase queries',
    active: true,
    created_at: new Date('2026-01-15T11:30:00Z').toISOString(),
  },
  {
    id: 'dept-other',
    name: 'Other',
    description: 'Miscellaneous inquiries and fresh campaign leads',
    active: true,
    created_at: new Date('2026-01-20T12:00:00Z').toISOString(),
  },
];

export const INITIAL_STATUSES: LeadStatus[] = [
  { id: 'stat-untouched', name: 'Untouched', category: 'New', display_order: 1, active: true, color: '#64748b', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-contacted', name: 'Contacted', category: 'In Progress', display_order: 2, active: true, color: '#3b82f6', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-followup', name: 'Follow-up', category: 'Follow-up', display_order: 3, active: true, color: '#f59e0b', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-callback', name: 'Call Back', category: 'Follow-up', display_order: 4, active: true, color: '#eab308', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-interested', name: 'Interested', category: 'In Progress', display_order: 5, active: true, color: '#10b981', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-hotlead', name: 'Hot Lead', category: 'In Progress', display_order: 6, active: true, color: '#ef4444', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-orderplaced', name: 'Order Placed', category: 'Converted', display_order: 7, active: true, color: '#059669', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-paymentpending', name: 'Payment Pending', category: 'In Progress', display_order: 8, active: true, color: '#f97316', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-moneyproblem', name: 'Money Problem', category: 'Follow-up', display_order: 9, active: true, color: '#8b5cf6', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-thinking', name: 'Thinking / Discussing', category: 'In Progress', display_order: 10, active: true, color: '#6366f1', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-noanswer', name: 'No Answer', category: 'In Progress', display_order: 11, active: true, color: '#94a3b8', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-busy', name: 'Busy', category: 'In Progress', display_order: 12, active: true, color: '#a8a29e', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-unreachable', name: 'Switch Off / Unreachable', category: 'In Progress', display_order: 13, active: true, color: '#78716c', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-notinterested', name: 'Not Interested', category: 'Lost', display_order: 14, active: true, color: '#dc2626', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-wrongnumber', name: 'Wrong Number', category: 'Lost', display_order: 15, active: true, color: '#b91c1c', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-duplicate', name: 'Duplicate Lead', category: 'Lost', display_order: 16, active: true, color: '#991b1b', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-donotcall', name: 'Do Not Call', category: 'Lost', display_order: 17, active: true, color: '#7f1d1d', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
  { id: 'stat-completed', name: 'Converted / Completed', category: 'Converted', display_order: 18, active: true, color: '#047857', created_at: new Date('2026-01-01T00:00:00Z').toISOString() },
];

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'user-admin',
    full_name: 'Super Admin',
    email: 'admin@essentialsoul.com',
    mobile: '9876543210',
    username: 'admin',
    role: 'ADMIN',
    active: true,
    department_ids: ['dept-ayurveda', 'dept-astrology', 'dept-homedecor', 'dept-reorder'],
    created_at: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'user-rahul',
    full_name: 'Rahul Sharma',
    email: 'rahul@essentialsoul.com',
    mobile: '9820011223',
    username: 'rahul.telecaller',
    role: 'TELECALLER',
    active: true,
    department_ids: ['dept-ayurveda'],
    created_at: new Date('2026-01-15T08:30:00Z').toISOString(),
  },
  {
    id: 'user-priya',
    full_name: 'Priya Patel',
    email: 'priya@essentialsoul.com',
    mobile: '9820022334',
    username: 'priya.telecaller',
    role: 'TELECALLER',
    active: true,
    department_ids: ['dept-astrology'],
    created_at: new Date('2026-01-16T08:30:00Z').toISOString(),
  },
  {
    id: 'user-amit',
    full_name: 'Amit Verma',
    email: 'amit@essentialsoul.com',
    mobile: '9820033445',
    username: 'amit.telecaller',
    role: 'TELECALLER',
    active: true,
    department_ids: ['dept-ayurveda', 'dept-homedecor'],
    created_at: new Date('2026-01-18T09:00:00Z').toISOString(),
  },
  {
    id: 'user-sneha',
    full_name: 'Sneha Singh',
    email: 'sneha@essentialsoul.com',
    mobile: '9820044556',
    username: 'sneha.telecaller',
    role: 'TELECALLER',
    active: true,
    department_ids: ['dept-reorder'],
    created_at: new Date('2026-02-01T09:30:00Z').toISOString(),
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-101',
    lead_number: 'ESL-1001',
    customer_name: 'Rohan Mehra',
    mobile: '9872134501',
    alternate_mobile: '9872134599',
    city: 'Jaipur',
    state: 'Rajasthan',
    product: 'Ayurvedic Joint Care Oil & Tablets (3-Month Pack)',
    amount: 2499,
    department_id: 'dept-ayurveda',
    source: 'Meta Ads',
    status_id: 'stat-untouched',
    assigned_to: 'user-rahul',
    assigned_at: new Date('2026-09-29T10:00:00Z').toISOString(),
    followup_date: null,
    followup_time: null,
    callback_date: null,
    callback_time: null,
    last_remark: null,
    last_activity_at: null,
    imported_at: new Date('2026-09-29T09:30:00Z').toISOString(),
    created_at: new Date('2026-09-29T09:30:00Z').toISOString(),
    updated_at: new Date('2026-09-29T10:00:00Z').toISOString(),
  },
  {
    id: 'lead-102',
    lead_number: 'ESL-1002',
    customer_name: 'Sunita Deshmukh',
    mobile: '9823456782',
    alternate_mobile: '',
    city: 'Pune',
    state: 'Maharashtra',
    product: 'Diabetes Reversal Herbal Kadha Combo',
    amount: 3200,
    department_id: 'dept-ayurveda',
    source: 'Google Ads',
    status_id: 'stat-followup',
    assigned_to: 'user-rahul',
    assigned_at: new Date('2026-09-28T11:00:00Z').toISOString(),
    followup_date: '2026-09-30',
    followup_time: '14:30',
    callback_date: null,
    callback_time: null,
    last_remark: 'Customer wants to discuss with son before placing order for 3 months',
    last_activity_at: new Date('2026-09-29T14:30:00Z').toISOString(),
    imported_at: new Date('2026-09-28T09:00:00Z').toISOString(),
    created_at: new Date('2026-09-28T09:00:00Z').toISOString(),
    updated_at: new Date('2026-09-29T14:30:00Z').toISOString(),
  },
  {
    id: 'lead-103',
    lead_number: 'ESL-1003',
    customer_name: 'Vikramaditya Roy',
    mobile: '9834567893',
    alternate_mobile: '9834567800',
    city: 'Kolkata',
    state: 'West Bengal',
    product: 'Vedic Kundali Dosha Remedies & Yellow Sapphire Guidance',
    amount: 5100,
    department_id: 'dept-astrology',
    source: 'Website Form',
    status_id: 'stat-interested',
    assigned_to: 'user-priya',
    assigned_at: new Date('2026-09-28T12:00:00Z').toISOString(),
    followup_date: '2026-10-01',
    followup_time: '11:00',
    callback_date: null,
    callback_time: null,
    last_remark: 'Shared birth details and horoscope chart. Highly interested in Shani Sade Sati remedy.',
    last_activity_at: new Date('2026-09-29T15:20:00Z').toISOString(),
    imported_at: new Date('2026-09-28T11:30:00Z').toISOString(),
    created_at: new Date('2026-09-28T11:30:00Z').toISOString(),
    updated_at: new Date('2026-09-29T15:20:00Z').toISOString(),
  },
  {
    id: 'lead-104',
    lead_number: 'ESL-1004',
    customer_name: 'Anjali Sharma',
    mobile: '9845678904',
    alternate_mobile: '',
    city: 'Bengaluru',
    state: 'Karnataka',
    product: 'Brass Ashtalakshmi Idol & Vastu Pyramid Set',
    amount: 4500,
    department_id: 'dept-homedecor',
    source: 'Instagram',
    status_id: 'stat-orderplaced',
    assigned_to: 'user-amit',
    assigned_at: new Date('2026-09-27T10:00:00Z').toISOString(),
    followup_date: null,
    followup_time: null,
    callback_date: null,
    callback_time: null,
    last_remark: 'Customer placed prepaid order for Diwali home sanctum. Dispatched via Express Courier.',
    last_activity_at: new Date('2026-09-29T16:00:00Z').toISOString(),
    imported_at: new Date('2026-09-27T09:00:00Z').toISOString(),
    created_at: new Date('2026-09-27T09:00:00Z').toISOString(),
    updated_at: new Date('2026-09-29T16:00:00Z').toISOString(),
    order_amount: 4500,
    order_product: 'Brass Ashtalakshmi Idol & Vastu Pyramid Set',
    order_quantity: 1,
    payment_status: 'Prepaid / UPI',
  },
  {
    id: 'lead-105',
    lead_number: 'ESL-1005',
    customer_name: 'Kavita Chawla',
    mobile: '9856789015',
    alternate_mobile: '',
    city: 'Delhi',
    state: 'Delhi',
    product: 'Ayurvedic Hair Vitalizer Tonic & Herbal Shampoo Pack',
    amount: 1899,
    department_id: 'dept-ayurveda',
    source: 'Meta Ads',
    status_id: 'stat-moneyproblem',
    assigned_to: 'user-rahul',
    assigned_at: new Date('2026-09-29T11:00:00Z').toISOString(),
    followup_date: '2026-10-05',
    followup_time: '12:00',
    callback_date: null,
    callback_time: null,
    last_remark: 'Salary arrives on 5th Oct. Requested call on salary day. Expected budget ₹1,500.',
    last_activity_at: new Date('2026-09-29T13:10:00Z').toISOString(),
    imported_at: new Date('2026-09-29T10:30:00Z').toISOString(),
    created_at: new Date('2026-09-29T10:30:00Z').toISOString(),
    updated_at: new Date('2026-09-29T13:10:00Z').toISOString(),
    expected_budget: 1500,
  },
  {
    id: 'lead-106',
    lead_number: 'ESL-1006',
    customer_name: 'Rajesh Gokhale',
    mobile: '9867890126',
    alternate_mobile: '',
    city: 'Nagpur',
    state: 'Maharashtra',
    product: 'Pure Shilajit Gold Resin & Ashwagandha Extract',
    amount: 2999,
    department_id: 'dept-ayurveda',
    source: 'Google Ads',
    status_id: 'stat-untouched',
    assigned_to: null, // UNASSIGNED!
    assigned_at: null,
    followup_date: null,
    followup_time: null,
    callback_date: null,
    callback_time: null,
    last_remark: null,
    last_activity_at: null,
    imported_at: new Date('2026-09-30T01:00:00Z').toISOString(),
    created_at: new Date('2026-09-30T01:00:00Z').toISOString(),
    updated_at: new Date('2026-09-30T01:00:00Z').toISOString(),
  },
  {
    id: 'lead-107',
    lead_number: 'ESL-1007',
    customer_name: 'Pooja Agarwal',
    mobile: '9878901237',
    alternate_mobile: '9878901200',
    city: 'Indore',
    state: 'Madhya Pradesh',
    product: 'Gemstone Emerald Ring Consultation',
    amount: 7500,
    department_id: 'dept-astrology',
    source: 'YouTube',
    status_id: 'stat-untouched',
    assigned_to: null, // UNASSIGNED!
    assigned_at: null,
    followup_date: null,
    followup_time: null,
    callback_date: null,
    callback_time: null,
    last_remark: null,
    last_activity_at: null,
    imported_at: new Date('2026-09-30T01:10:00Z').toISOString(),
    created_at: new Date('2026-09-30T01:10:00Z').toISOString(),
    updated_at: new Date('2026-09-30T01:10:00Z').toISOString(),
  },
  {
    id: 'lead-108',
    lead_number: 'ESL-1008',
    customer_name: 'Deepak Nair',
    mobile: '9889012348',
    alternate_mobile: '',
    city: 'Kochi',
    state: 'Kerala',
    product: 'Ayurvedic Liver Detox & Fatty Liver Cleanse',
    amount: 2199,
    department_id: 'dept-ayurveda',
    source: 'Meta Ads',
    status_id: 'stat-untouched',
    assigned_to: null, // UNASSIGNED!
    assigned_at: null,
    followup_date: null,
    followup_time: null,
    callback_date: null,
    callback_time: null,
    last_remark: null,
    last_activity_at: null,
    imported_at: new Date('2026-09-30T01:15:00Z').toISOString(),
    created_at: new Date('2026-09-30T01:15:00Z').toISOString(),
    updated_at: new Date('2026-09-30T01:15:00Z').toISOString(),
  },
  {
    id: 'lead-109',
    lead_number: 'ESL-1009',
    customer_name: 'Manoj Kumar',
    mobile: '9890123459',
    alternate_mobile: '',
    city: 'Chandigarh',
    state: 'Punjab',
    product: 'Thyroid Care Herbal Tablets',
    amount: 1799,
    department_id: 'dept-reorder',
    source: 'Reorder SMS',
    status_id: 'stat-callback',
    assigned_to: 'user-sneha',
    assigned_at: new Date('2026-09-29T10:00:00Z').toISOString(),
    followup_date: '2026-09-30',
    followup_time: '16:00',
    callback_date: '2026-09-30',
    callback_time: '16:00',
    last_remark: 'Requested callback after 4 PM when free from office meetings',
    last_activity_at: new Date('2026-09-29T11:45:00Z').toISOString(),
    imported_at: new Date('2026-09-29T09:00:00Z').toISOString(),
    created_at: new Date('2026-09-29T09:00:00Z').toISOString(),
    updated_at: new Date('2026-09-29T11:45:00Z').toISOString(),
  },
  {
    id: 'lead-110',
    lead_number: 'ESL-1010',
    customer_name: 'Harish Chander',
    mobile: '9812345670',
    alternate_mobile: '',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    product: 'Vedic Rudraksha Mala (Original Panchmukhi)',
    amount: 2800,
    department_id: 'dept-astrology',
    source: 'Google Ads',
    status_id: 'stat-hotlead',
    assigned_to: 'user-priya',
    assigned_at: new Date('2026-09-29T14:00:00Z').toISOString(),
    followup_date: '2026-09-30',
    followup_time: '12:30',
    callback_date: null,
    callback_time: null,
    last_remark: 'Urgent requirement for parent blessing ceremony this weekend. Ready to buy today.',
    last_activity_at: new Date('2026-09-29T16:30:00Z').toISOString(),
    imported_at: new Date('2026-09-29T12:00:00Z').toISOString(),
    created_at: new Date('2026-09-29T12:00:00Z').toISOString(),
    updated_at: new Date('2026-09-29T16:30:00Z').toISOString(),
  }
];

export const INITIAL_ACTIVITIES: LeadActivity[] = [
  {
    id: 'act-1',
    lead_id: 'lead-102',
    user_id: 'user-rahul',
    user_name: 'Rahul Sharma',
    old_status_id: 'stat-untouched',
    old_status_name: 'Untouched',
    new_status_id: 'stat-followup',
    new_status_name: 'Follow-up',
    remark: 'Customer wants to discuss with son before placing order for 3 months',
    activity_type: 'FOLLOWUP_SCHEDULED',
    created_at: new Date('2026-09-29T14:30:00Z').toISOString(),
  },
  {
    id: 'act-2',
    lead_id: 'lead-103',
    user_id: 'user-priya',
    user_name: 'Priya Patel',
    old_status_id: 'stat-untouched',
    old_status_name: 'Untouched',
    new_status_id: 'stat-interested',
    new_status_name: 'Interested',
    remark: 'Shared birth details and horoscope chart. Highly interested in Shani Sade Sati remedy.',
    activity_type: 'STATUS_UPDATE',
    created_at: new Date('2026-09-29T15:20:00Z').toISOString(),
  },
  {
    id: 'act-3',
    lead_id: 'lead-104',
    user_id: 'user-amit',
    user_name: 'Amit Verma',
    old_status_id: 'stat-interested',
    old_status_name: 'Interested',
    new_status_id: 'stat-orderplaced',
    new_status_name: 'Order Placed',
    remark: 'Customer placed prepaid order for Diwali home sanctum. Dispatched via Express Courier.',
    activity_type: 'ORDER_PLACED',
    order_data: {
      amount: 4500,
      product: 'Brass Ashtalakshmi Idol & Vastu Pyramid Set',
      quantity: 1,
      payment_status: 'Prepaid / UPI',
    },
    created_at: new Date('2026-09-29T16:00:00Z').toISOString(),
  },
  {
    id: 'act-4',
    lead_id: 'lead-105',
    user_id: 'user-rahul',
    user_name: 'Rahul Sharma',
    old_status_id: 'stat-untouched',
    old_status_name: 'Untouched',
    new_status_id: 'stat-moneyproblem',
    new_status_name: 'Money Problem',
    remark: 'Salary arrives on 5th Oct. Requested call on salary day. Expected budget ₹1,500.',
    activity_type: 'STATUS_UPDATE',
    order_data: {
      budget: 1500,
    },
    created_at: new Date('2026-09-29T13:10:00Z').toISOString(),
  },
  {
    id: 'act-5',
    lead_id: 'lead-109',
    user_id: 'user-sneha',
    user_name: 'Sneha Singh',
    old_status_id: 'stat-untouched',
    old_status_name: 'Untouched',
    new_status_id: 'stat-callback',
    new_status_name: 'Call Back',
    remark: 'Requested callback after 4 PM when free from office meetings',
    activity_type: 'CALL',
    created_at: new Date('2026-09-29T11:45:00Z').toISOString(),
  },
  {
    id: 'act-6',
    lead_id: 'lead-110',
    user_id: 'user-priya',
    user_name: 'Priya Patel',
    old_status_id: 'stat-untouched',
    old_status_name: 'Untouched',
    new_status_id: 'stat-hotlead',
    new_status_name: 'Hot Lead',
    remark: 'Urgent requirement for parent blessing ceremony this weekend. Ready to buy today.',
    activity_type: 'STATUS_UPDATE',
    created_at: new Date('2026-09-29T16:30:00Z').toISOString(),
  }
];

export const INITIAL_FOLLOWUPS: Followup[] = [
  {
    id: 'fol-1',
    lead_id: 'lead-102',
    user_id: 'user-rahul',
    customer_name: 'Sunita Deshmukh',
    customer_mobile: '9823456782',
    product: 'Diabetes Reversal Herbal Kadha Combo',
    followup_type: 'FOLLOW_UP',
    scheduled_date: '2026-09-30',
    scheduled_time: '14:30',
    remark: 'Discuss with son before ordering',
    status: 'PENDING',
    created_at: new Date('2026-09-29T14:30:00Z').toISOString(),
  },
  {
    id: 'fol-2',
    lead_id: 'lead-103',
    user_id: 'user-priya',
    customer_name: 'Vikramaditya Roy',
    customer_mobile: '9834567893',
    product: 'Vedic Kundali Dosha Remedies',
    followup_type: 'FOLLOW_UP',
    scheduled_date: '2026-10-01',
    scheduled_time: '11:00',
    remark: 'Review remedy gemstone chart with family',
    status: 'PENDING',
    created_at: new Date('2026-09-29T15:20:00Z').toISOString(),
  },
  {
    id: 'fol-3',
    lead_id: 'lead-109',
    user_id: 'user-sneha',
    customer_name: 'Manoj Kumar',
    customer_mobile: '9890123459',
    product: 'Thyroid Care Herbal Tablets',
    followup_type: 'CALL_BACK',
    scheduled_date: '2026-09-30',
    scheduled_time: '16:00',
    remark: 'Requested callback after 4 PM',
    status: 'PENDING',
    created_at: new Date('2026-09-29T11:45:00Z').toISOString(),
  },
  {
    id: 'fol-4',
    lead_id: 'lead-110',
    user_id: 'user-priya',
    customer_name: 'Harish Chander',
    customer_mobile: '9812345670',
    product: 'Vedic Rudraksha Mala',
    followup_type: 'FOLLOW_UP',
    scheduled_date: '2026-09-30',
    scheduled_time: '12:30',
    remark: 'Ready to buy today for weekend ceremony',
    status: 'PENDING',
    created_at: new Date('2026-09-29T16:30:00Z').toISOString(),
  }
];
